

CC=gcc
CFLAGS=-std=gnu11 -g -pedantic -Wall

all: day03_1 day03_2

day03_1: day03_1.c
	$(CC) $(CFLAGS) day03_1.c -o day03_1

day03_2: day03_2.c
	$(CC) $(CFLAGS) day03_2.c -o day03_2

.PHONY: clean
clean:
	rm -f day03_1 day03_2
