CC=gcc
CFLAGS=-std=gnu11 -g -pedantic -Wall

all: day08_1 day08_2

day08_1: day08_1.c
	$(CC) $(CFLAGS) day08_1.c -o day08_1

day08_2: day08_2.c
	$(CC) $(CFLAGS) day08_2.c -o day08_2

.PHONY: clean
clean:
	rm -f day08_1 day08_2
